version: '3.3'

services:
   db_gradient:
     image: mysql:5.7
     volumes:
       - data_gradient:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wp_gradient:
     depends_on:
       - db_gradient
     image: wordpress:latest
     volumes:
       - ./theme/:/var/www/html/wp-content/themes/gradient/
     ports:
       - "9090:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db_gradient:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
volumes:
    data_gradient: {}